### PR TITLE
Add mimir read dashboard

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
Towards https://github.com/giantswarm/roadmap/issues/3162

This PR adds the mixins dashboards for mimir read path

### Checklist

- [x] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Where are my screenshots? :)

**Comment by QuantumEnigmaa** [comment]
* networking dashboard : 
image

* resources dashboard (except disk usage) : 
image

This specific graph is also missing but I don't think this is that much of an issue : 
image

* base dashboard : 
image

Missing some data for `query-frontend` latency and headlines graphs. Need to sor this out

**Comment by QuantumEnigmaa** [comment]
The headline graphs are showing data at what appears to be random times. However concerning the `query-frontend` graph the issue is a strange one : the recording rule used in the query isn't working but if one replaces it with the actual query being called by the recording rule, it works.
Unfortunately as of now, I wasn't able to find the root cause to this issue. 

I thus suggest merging this for now and create a dedicated issue on Atlas board to track this recording rule issue. That way I can move to the other dashboards.

**Comment by QuantumEnigmaa** [comment]
circle-ci is failing but the error message is a bit vague : 
```
Validating against kubernetes version 1.20.0
walk.go:74: found symbolic link in path: /root/project/helm/dashboards/charts/private_dashboards_al/templates/configmap-dashboards.yaml resolves to /root/project/helm/dashboards/templates/configmap-dashboards.yaml
walk.go:74: found symbolic link in path: /root/project/helm/dashboards/charts/private_dashboards_mz/templates/configmap-dashboards.yaml resolves to /root/project/helm/dashboards/templates/configmap-dashboards.yaml
walk.go:74: found symbolic link in path: /root/project/helm/dashboards/charts/public_dashboards/templates/configmap-dashboards.yaml resolves to /root/project/helm/dashboards/templates/configmap-dashboards.yaml
Validating against kubernetes version 1.21.0
walk.go:74: found symbolic link in path: /root/project/helm/dashboards/charts/private_dashboards_al/templates/configmap-dashboards.yaml resolves to /root/project/helm/dashboards/templates/configmap-dashboards.yaml
walk.go:74: found symbolic link in path: /root/project/helm/dashboards/charts/private_dashboards_mz/templates/configmap-dashboards.yaml resolves to /root/project/helm/dashboards/templates/configmap-dashboards.yaml
walk.go:74: found symbolic link in path: /root/project/helm/dashboards/charts/public_dashboards/templates/configmap-dashboards.yaml resolves to /root/project/helm/dashboards/templates/configmap-dashboards.yaml
Validating against kubernetes version 1.22.0
walk.go:74: found symbolic link in path: /root/project/helm/dashboards/charts/private_dashboards_al/templates/configmap-dashboards.yaml resolves to /root/project/helm/dashboards/templates/configmap-dashboards.yaml
walk.go:74: found symbolic link in path: /root/project/helm/dashboards/charts/private_dashboards_mz/templates/configmap-dashboards.yaml resolves to /root/project/helm/dashboards/templates/configmap-dashboards.yaml
walk.go:74: found symbolic link in path: /root/project/helm/dashboards/charts/public_dashboards/templates/configmap-dashboards.yaml resolves to /root/project/helm/dashboards/templates/configmap-dashboards.yaml
Validating against kubernetes version 1.23.0
walk.go:74: found symbolic link in path: /root/project/helm/dashboards/charts/private_dashboards_al/templates/configmap-dashboards.yaml resolves to /root/project/helm/dashboards/templates/configmap-dashboards.yaml
walk.go:74: found symbolic link in path: /root/project/helm/dashboards/charts/private_dashboards_mz/templates/configmap-dashboards.yaml resolves to /root/project/helm/dashboards/templates/configmap-dashboards.yaml
walk.go:74: found symbolic link in path: /root/project/helm/dashboards/charts/public_dashboards/templates/configmap-dashboards.yaml resolves to /root/project/helm/dashboards/templates/configmap-dashboards.yaml
stdin - failed validation: error unmarshalling resource: error converting YAML to JSON: yaml: line 576: mapping values are not allowed in this context
```

**Pull request merged**
