### PR TITLE
fix mimir writes resources disk usage dashboard's graphs

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
Towards https://github.com/giantswarm/giantswarm/issues/30090

The graphs for Disk reads and Disk writes also display data for the non-PV storage used by the ingesters for the `/etc/mimir` path but as the graphs are showing the expected data anyway, this "noise" can just be ignored.

### Checklist

- [x] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Comment by QuantumEnigmaa** [comment]
Before : 
image


After : 
image

**Comment by QuantumEnigmaa** [comment]
Had someone removed this dashboard ? Nothing mentions such a thing in the changelog but this PR makes it appear as if I was adding a brand new file

**Review by QuentinBisson — APPROVED** [review]

**Review by QuentinBisson — CHANGES_REQUESTED** [review]
Oh it's not in the correct path, the mimir dashboard should be here https://github.com/giantswarm/dashboards/tree/main/helm/dashboards/charts/private_dashboards_mz/dashboards/shared/private not in the al folder

**Comment by QuentinBisson** [comment]
Can you reformat using vscode and CTRL shift I ?

**Comment by QuantumEnigmaa** [comment]
> Can you reformat using vscode and CTRL shift I ?

Well I don't mind but nothing happens :/

**Comment by QuentinBisson** [comment]
I'll run it tomorrow. I Guess we don't have thé same formatters 😅

**Review by QuentinBisson — APPROVED** [review]
Approving now but let's wait tomorrow

**Comment by hervenicol** [comment]
> Can you reformat using vscode and CTRL shift I ?

Why should we manually change these files? I guess they were exported from Grafana, I'm in favor of keeping them as-is.
If we add some manual things like changes in indentation, we will lose this next time we export them from Grafana.

**Comment by QuentinBisson** [comment]
Thé thing is we all have custom indentation and reviewing makes it really hard, so we need to standardize

**Comment by hervenicol** [comment]
> Thé thing is we all have custom indentation and reviewing makes it really hard, so we need to standardize

For "handwritten" code I agree, but for generated one like the dashboards I'm don't see the point.

**Comment by QuentinBisson** [comment]
It's easy, if I edit the expression in the file, my formatter will rewrite everything

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Btw, I think this should be fixed by automation and not me coming to format files :D

**Comment by QuentinBisson** [comment]
Adding automation here https://github.com/giantswarm/dashboards/pull/509

**Comment by QuantumEnigmaa** [comment]
@QuentinBisson @hervenicol are we good to merge here ?

**Comment by QuentinBisson** [comment]
I'm fine yes

**Comment by QuantumEnigmaa** [comment]
> Didn't find the documentation about what we changed from upstream mixins, so we can apply it back next time we import the Mimir mixins.

If you mean what changed compared to the original upstream mixin dashboard, I changed the `cluster` labels used in the Disk storage graphs' queries to `cluster_id` as well as uptading the global `cluster` parameter for the whole dashboard from `label_values(cortex_build_info, cluster)` to `"abel_values(mimir_build_info, cluster_id)`

So I guess it's mainly a custom change from our side which is not relevant for upstream (except for the the `cortex` to `mimir` change maybe)

**Pull request merged**
