### PR TITLE
Add ConfigMap for OpenStack public dashboards

### PR DESCRIPTION
**Pull request by tfussell**
Towards https://github.com/giantswarm/roadmap/issues/640

This PR

- Changes templates to create public dashboard ConfigMap based on provider name instead of per-provider conditional rendering.

### Checklist

- [x] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Review by pipo02mix — APPROVED** [review]
nice improvement

**Review by QuentinBisson — APPROVED** [review]
LGTM if tested

**Review by TheoBrigitte — APPROVED** [review]
Nice one

**Comment by tfussell** [comment]
Tested on `gamma`:
```
# Source: dashboards/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: "dashboards"
    app.kubernetes.io/instance: "dashboards"
    app.giantswarm.io/branch: "add-openstack"
    app.giantswarm.io/commit: "77fc5b81794073df8994b56921c456762a1ec991"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "1.9.1-77fc5b81794073df8994b56921c456762a1ec991"
    helm.sh/chart: "dashboards-1.9.1-77fc5b81794073df8994b56921c456762a1ec991"
    giantswarm.io/service-type: managed  
  name: grafana-dashboards-public-openstack
  namespace: monitoring
data:
  {}
```

**Comment by tfussell** [comment]
I tested it on `gopher` (KVM) because KVM has provider-specific dashboards. There I found that the glob was not working (CM was empty). I followed https://github.com/helm/helm/issues/3593#issuecomment-369961569 and now it's working on KVM as well:

```
---
# Source: dashboards/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: "dashboards"
    app.kubernetes.io/instance: "dashboards"
    app.giantswarm.io/branch: "add-openstack"
    app.giantswarm.io/commit: "5a981b4009e8119d049ad0d3eb568ce456076b21"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "1.9.1-5a981b4009e8119d049ad0d3eb568ce456076b21"
    helm.sh/chart: "dashboards-1.9.1-5a981b4009e8119d049ad0d3eb568ce456076b21"
    giantswarm.io/service-type: managed  
  name: grafana-dashboards-public-kvm
  namespace: monitoring
data:
  kvm-machine-usage.json: |
    {
      "annotations": {
...
```

**Pull request merged**
