### PR TITLE
Add new public dashboard for KVM usage

### PR DESCRIPTION
**Pull request by pipo02mix**
This PR

- adds/changes/removes etc

### Checklist

- [x] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Comment by pipo02mix** [comment]
Adding screenshots
Screenshot 2021-07-22 at 12 09 19
Screenshot 2021-07-22 at 12 09 34
Screenshot 2021-07-22 at 12 09 49
Screenshot 2021-07-22 at 12 10 21

**Comment by QuentinBisson** [comment]
I'd say we can start with this but I would like it if @sig-ux and especially @marians could take a look at the dashboard ux wise :)

**Comment by pipo02mix** [comment]
Sure this board was created originally by Marian. I review the UX recommendation but happy to received more feedback

**Comment by mig4** [comment]
Yeah, this is moved from `g8s-grafana` right?

**Review by mig4 — APPROVED** [review]

**Comment by marians** [comment]
@JosephSalisbury We need to figure out how to link to this dashboard from the public Home dashboard, as this one (I reckon) is provider specific and it won't exist in AWS and Azure installations.

**Comment by QuentinBisson** [comment]
You can add the dashboard under helm/dashboards/dashboards/kvm as defined in https://github.com/giantswarm/dashboards/blob/0234e7766ef75c4ea65405aa9bd5f8c2b70daf15/helm/dashboards/templates/configmap.yaml#L54

**Comment by pipo02mix** [comment]
it this enough?
https://github.com/giantswarm/dashboards/pull/43/files

**Comment by QuentinBisson** [comment]
Yes :)

**Pull request merged**
