### PR TITLE
add-editor-config

### PR DESCRIPTION
**Pull request by QuentinBisson**
This PR

- adds an editorconfig file. For vscode users, you will need to install the editorconfig plugin

### Checklist

- [ ] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Comment by QuentinBisson** [comment]
@TheoBrigitte or @hervenicol could I have some eyes on the shellcheck fixes?

**Comment by hervenicol** [comment]
Wow....

So, it's been decided that your editor could tamper grafana-exported dashboards at commit? I guess it's towards https://github.com/giantswarm/dashboards/pull/502 .
And it also runs shellcheck?
And you updated all the shell scripts that had shellscript alerts?

Most of these changes look legit, some will slightly change the script's behaviour but it looks like it was probably broken before.
I trust you for testing these all.

**Comment by marians** [comment]
My understanding is that this PR is adding the editorconfig and pre-commit action but it's not enforcing a certain JSON style in CI, correct?

**Review by marians — COMMENTED** [review]
I think the change on `helm/dashboards/values.schema.json` is problematic, as these files are usually generated using [helm-schema-gen](https://github.com/karuppiah7890/helm-schema-gen) and that tool has its own indentation setting of 4 spaces. So updating the schema will become more painful.

**Comment by QuentinBisson** [comment]
@hervenicol no this has not been decided at all :) we can discuss this 😅

**Comment by QuentinBisson** [comment]
I removed shellcheck changes to keep the conversation to the main topic which is json formatting

**Review by marians — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Team is not in favor of this, closing

**Pull request closed without merging**
