### PR TITLE
add Grafana Analytics dashboard

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/roadmap/issues/383

This PR adds Grafana Analytics dashboard, which shows installation Grafana dashboards usage.

### CODE REVIEW

**Comment by TheoBrigitte** [comment]
image

**Review by QuentinBisson — APPROVED** [review]

**Comment by TheoBrigitte** [comment]
Based this dashboard on upstream one: https://github.com/MacroPower/macropower-analytics-panel/blob/master/example/server/dashboards/Grafana%20Analytics.json

**Comment by TheoBrigitte** [comment]
Data looks wrong cause they use this recording rule
```
      - record: :grafana_analytics_sessions_total:increase60s
        expr: increase(grafana_analytics_sessions_total[60s]) / (132 / 99)
```

**Comment by TheoBrigitte** [comment]
Going with this as first version. But happy to elaborate more on this dashboard later.

**Pull request merged**
