### PR TITLE
Add analytics-panel to public dashboards

### PR DESCRIPTION
**Pull request by mig4**
Add analytics panel to all public dashboards so we can get some usage
data to help us guide development planning.

Closes: https://github.com/giantswarm/roadmap/issues/379

### Checklist

- [ ] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]
LGTM but I cannot read dashboards ;D

**Comment by mig4** [comment]
This depends on https://github.com/giantswarm/g8s-grafana/pull/326 so should only be merged after that one is (because without the plugin in grafana, dashboards which use the panel that it adds would show errors).

**Review by TheoBrigitte — APPROVED** [review]
LGTM

Found out that my ad blocker (uBlock origin) is blocking the request to the backend.

**Comment by mig4** [comment]
> Found out that my ad blocker (uBlock origin) is blocking the request to the backend.

Interesting, did you ever find out why? Is it something to do with the word `analytics` in the URL? Kinda not ideal 😉

**Pull request merged**
