### PR TITLE
Add AWS Cluster Status Dashboard

### PR DESCRIPTION
**Pull request by anvddriesch**
Towards https://github.com/giantswarm/giantswarm/issues/18591

This PR

Adds AWS Cluster Status Dashboard from the g8s-grafana repo

### Checklist

- [ ] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Review by njuettner — APPROVED** [review]
Not looking into `json` but I guess it's fine :D

**Comment by anvddriesch** [comment]
I just copied it from the other repo so it SHOULD look the same as the private one :smile:

**Comment by marians** [comment]
Just noticed that the dashboard does not appear in the list on the Home dashboard:

image

**Comment by anvddriesch** [comment]
I did not know we had this since I just moved the dashboard from private to public! :) Do you know how to add it?

**Pull request merged**
