### PR TITLE
Add FluxCD dashboards

### PR DESCRIPTION
**Pull request by kubasobon**
Towards giantswarm/giantswarm#19449 and giantswarm/giantswarm#19455
This PR

- adds FluxCD dashboards

### Checklist

- [x] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]
LGTM IF tested

**Review by MarcelMue — APPROVED** [review]
Are these created by yourself or is there an upstream source for them?

**Comment by kubasobon** [comment]
Source: https://github.com/fluxcd/flux2/tree/v0.21.0/manifests/monitoring/grafana/dashboards
I mentioned it in a commit message as well.

**Comment by kubasobon** [comment]
Tested on `ginger`.

**Comment by MarcelMue** [comment]
We should somehow think about keeping these up to date with upstream but I have no easy solution for this

**Pull request merged**
