### PR TITLE
 Add Managed Apps Usage dashboard

### PR DESCRIPTION
**Pull request by rossf7**
Towards https://github.com/giantswarm/roadmap/issues/322

This PR

- Adds Managed Apps Usage dashboard.

### Checklist

- [x] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Comment by rossf7** [comment]
Screen Shot 2021-09-08 at 11 52 32 AM

Tested on ghost

**Comment by QuentinBisson** [comment]
Can you add the analytics panel as well ?

**Comment by rossf7** [comment]
@QuentinBisson My bad I thought I'd added it. 😅 
It's there now.

**Review by QuentinBisson — APPROVED** [review]
Thanks @rossf7 Once everything is moved to jsonnet, adding the plugin will be done automatically :D

**Pull request merged**
