### PR TITLE
Fix duplicate series in match group in cost estimation

### PR DESCRIPTION
**Pull request by QuentinBisson**
This PR

- fixes a panel in the prometehus cost estimation dashboard
- screenshots before:
image

- screenshots after:
image

### Checklist

- [x] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Comment by hervenicol** [comment]
What are the 32GB dots in the "after" screenshot?

**Comment by QuentinBisson** [comment]
The node memory

**Comment by QuentinBisson** [comment]
The cluster_id makes sure this works for mc nodes only
The sum fixes issues where we have multiple prometheus running on the same node which happens quite often on grizzly because prometheus comes and goes with every cluster

**Comment by hervenicol** [comment]
Oh, so the node memory was not showing before in some cases!

But now it does not look very nice, it looks like lots of small segments. That's what the "max" was supposed to do IIRC: have only one line.

And the `sum`: isn't there a risk if it gets 2 nodes that we get double the actual amount of RAM?

**Comment by QuentinBisson** [comment]
It's not nice because on grizzly, we have a lot of prometheus. So we could change this by showing the limits of all nodes (not caring if they run a prometheus or not) but also this will go away soon with mimir anyway :D

As for the sum, not really because of the `by (cluster_id, node)` and because of the join on the kube_pod_info metric (which requires the pod so the node is on the MC)

**Comment by hervenicol** [comment]
I can't wrap my head around it, and I can't even reproduce the issue.
So I'll trust you on it.

BTW we've got a very similar graph in `prometheus` dashboard:
image
...and the query is nearly the same. Maybe has the same issue (that I can't see on my laptop today :rofl: :shrug: )

**Review by hervenicol — APPROVED** [review]
If it works for you it works for me :sweat_smile:

**Comment by QuentinBisson** [comment]
To be fair, i've only seen this on grizzly when I use a 2d minimium duration in grafana

**Pull request merged**
