### PR TITLE
Upgrade deprecated panels

### PR DESCRIPTION
**Pull request by QuentinBisson**
Migrate old angular panels

### Checklist

- [x] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Comment by hervenicol** [comment]
I guess you basically opened each of these with Grafana 11, then exported them and updated them on the repo?

**Comment by hervenicol** [comment]
oh, and also it seems some files were moved/renamed.

**Comment by QuentinBisson** [comment]
I did using grafana 10 because when I opened a few in grafana 11 I got errors :D 

Yes I moved some from the aws only to shared because they are also used in CAPA. It could have been done in another PR  though :(

**Comment by QuentinBisson** [comment]
But main idea is open in grafana, click the individual migrate buttons save and replace datasource with default

**Review by hervenicol — APPROVED** [review]
:+1:

**Pull request merged**
