### PR TITLE
Add kong ingress controller dashboard

### PR DESCRIPTION
**Pull request by ubergesundheit**
This PR

- Adds a dashboard for kong ingress controller

### Checklist

- [x] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Review by Gacko — APPROVED** [review]
Guess this is mostly copy & paste, so basically fine. Maybe Atlas has some input on Giant Swarm specific stuff. :)

**Review by hervenicol — APPROVED** [review]
Well, if it is official and maintained, and works as-is from the grafana dashboards library, great!
LGTM if tested.

Hard to review the dashboards. Would be great to have before/after screenshot, to better understand what has changed.

**Comment by ubergesundheit** [comment]
This is based on an official dashboard. I've added the Giant Swarm tracking panel and cluster and namespace selectors.

Here is a diff between the official and the version in this repo

```diff
2,3c2,12
<   "__inputs": [],
<   "__elements": [],
---
>   "__inputs": [
>     {
>       "name": "DS_PROMETHEUS",
>       "label": "Prometheus",
>       "description": "",
>       "type": "datasource",
>       "pluginId": "prometheus",
>       "pluginName": "Prometheus"
>     }
>   ],
>   "__elements": {},
9c18
<       "version": "8.3.4"
---
>       "version": "9.2.5"
18a28,39
>       "id": "macropower-analytics-panel",
>       "name": "Analytics Panel",
>       "version": "2.1.0"
>     },
>     {
>       "type": "datasource",
>       "id": "prometheus",
>       "name": "Prometheus",
>       "version": "1.0.0"
>     },
>     {
>       "type": "panel",
28c49,52
<         "datasource": "-- Grafana --",
---
>         "datasource": {
>           "type": "datasource",
>           "uid": "grafana"
>         },
44a69
>   "gnetId": 15662,
50a76,108
>       "datasource": {
>         "type": "prometheus",
>         "uid": "${DS_PROMETHEUS}"
>       },
>       "gridPos": {
>         "h": 1,
>         "w": 24,
>         "x": 0,
>         "y": 0
>       },
>       "id": 14,
>       "options": {
>         "analyticsOptions": {
>           "dashboard": "$__dashboard",
>           "flatten": false,
>           "heartbeatAlways": false,
>           "heartbeatInterval": 60,
>           "postEnd": false,
>           "postHeartbeat": false,
>           "postStart": true,
>           "server": "/analytics-plugin/write",
>           "showDetails": false
>         }
>       },
>       "title": "  ",
>       "transparent": true,
>       "type": "macropower-analytics-panel"
>     },
>     {
>       "datasource": {
>         "type": "prometheus",
>         "uid": "${DS_PROMETHEUS}"
>       },
104c162
<         "y": 0
---
>         "y": 1
112c170,171
<           "placement": "bottom"
---
>           "placement": "bottom",
>           "showLegend": true
116a176,180
>           "datasource": {
>             "type": "prometheus",
>             "uid": "${DS_PROMETHEUS}"
>           },
>           "editorMode": "code",
118c182
<           "expr": "ingress_controller_configuration_push_duration_milliseconds_bucket",
---
>           "expr": "ingress_controller_configuration_push_duration_milliseconds_bucket{cluster_id=\"$cluster\", namespace=\"$namespace\"}",
120a185
>           "range": true,
127a193,196
>       "datasource": {
>         "type": "prometheus",
>         "uid": "${DS_PROMETHEUS}"
>       },
151c220
<         "y": 0
---
>         "y": 1
169c238
<       "pluginVersion": "8.3.4",
---
>       "pluginVersion": "9.2.5",
171a241,245
>           "datasource": {
>             "type": "prometheus",
>             "uid": "${DS_PROMETHEUS}"
>           },
>           "editorMode": "code",
173c247
<           "expr": "ingress_controller_configuration_push_count{success=\"true\"}",
---
>           "expr": "ingress_controller_configuration_push_count{success=\"true\",cluster_id=\"$cluster\", namespace=\"$namespace\"}",
176a251
>           "range": true,
183a259,262
>       "datasource": {
>         "type": "prometheus",
>         "uid": "${DS_PROMETHEUS}"
>       },
216c295
<         "y": 4
---
>         "y": 5
234c313
<       "pluginVersion": "8.3.4",
---
>       "pluginVersion": "9.2.5",
236a316,320
>           "datasource": {
>             "type": "prometheus",
>             "uid": "${DS_PROMETHEUS}"
>           },
>           "editorMode": "code",
238c322
<           "expr": "sum by (failure_reason) (ingress_controller_configuration_push_count{success=\"false\"})",
---
>           "expr": "sum by (failure_reason) (ingress_controller_configuration_push_count{success=\"false\", cluster_id=\"$cluster\", namespace=\"$namespace\"})",
248a333,336
>       "datasource": {
>         "type": "prometheus",
>         "uid": "${DS_PROMETHEUS}"
>       },
272c360
<         "y": 8
---
>         "y": 9
290c378
<       "pluginVersion": "8.3.4",
---
>       "pluginVersion": "9.2.5",
292a381,385
>           "datasource": {
>             "type": "prometheus",
>             "uid": "${DS_PROMETHEUS}"
>           },
>           "editorMode": "code",
294c387
<           "expr": "ingress_controller_translation_count{success=\"true\"}",
---
>           "expr": "ingress_controller_translation_count{success=\"true\", cluster_id=\"$cluster\", namespace=\"$namespace\"}",
296a390
>           "range": true,
303a398,401
>       "datasource": {
>         "type": "prometheus",
>         "uid": "${DS_PROMETHEUS}"
>       },
331c429
<         "y": 12
---
>         "y": 13
349c447
<       "pluginVersion": "8.3.4",
---
>       "pluginVersion": "9.2.5",
351a450,453
>           "datasource": {
>             "type": "prometheus",
>             "uid": "${DS_PROMETHEUS}"
>           },
364c466
<   "schemaVersion": 34,
---
>   "schemaVersion": 37,
368c470,515
<     "list": []
---
>     "list": [
>       {
>         "current": {},
>         "datasource": {
>           "type": "prometheus",
>           "uid": "${DS_PROMETHEUS}"
>         },
>         "definition": "label_values(ingress_controller_configuration_push_duration_milliseconds_bucket, cluster_id)",
>         "hide": 0,
>         "includeAll": true,
>         "multi": false,
>         "name": "cluster",
>         "options": [],
>         "query": {
>           "query": "label_values(ingress_controller_configuration_push_duration_milliseconds_bucket, cluster_id)",
>           "refId": "StandardVariableQuery"
>         },
>         "refresh": 1,
>         "regex": "",
>         "skipUrlSync": false,
>         "sort": 0,
>         "type": "query"
>       },
>       {
>         "current": {},
>         "datasource": {
>           "type": "prometheus",
>           "uid": "${DS_PROMETHEUS}"
>         },
>         "definition": "label_values(ingress_controller_configuration_push_duration_milliseconds_bucket{cluster_id=\"$cluster\"}, namespace)",
>         "hide": 0,
>         "includeAll": true,
>         "multi": false,
>         "name": "namespace",
>         "options": [],
>         "query": {
>           "query": "label_values(ingress_controller_configuration_push_duration_milliseconds_bucket{cluster_id=\"$cluster\"}, namespace)",
>           "refId": "StandardVariableQuery"
>         },
>         "refresh": 1,
>         "regex": "",
>         "skipUrlSync": false,
>         "sort": 0,
>         "type": "query"
>       }
>     ]
377,380c524,527
<   "uid": "SaGwMOtnz",
<   "version": 2,
<   "gnetId": 15662
< }
\ No newline at end of file
---
>   "uid": "SaGwMOtny",
>   "version": 6,
>   "weekStart": ""
> }
```

**Review by ced0ps — APPROVED** [review]
LGTM IT

**Pull request merged**
