### PR TITLE
Add Grizzly/Jsonnet workflows for Grafana Cloud dashboards

### PR DESCRIPTION
**Pull request by mig4**
This adds grizzly and jsonnet support to help avoid repetition, allow
component re-use, etc. and to provide new workflows for developing
dashboards in Jsonnet locally and being able to diff/preview/apply to
Grafana Cloud.

### Add jsonnet-bundler

To start with, add jsonnet-bundler project file with dependency
definitions (generated with `jb init` and `jb install
https://github.com/grafana/grafonnet-lib/grafonnet`), and a
`Makefile.dashboards.mk` that adds `vendor` target which calls `jb
install` so dependencies can be installed based on the generated
definitions.

### Use _tool dependency tracking_

As this doesn't require having `jsonnet-bundler` (or other Go tools)
pre-installed, instead they're fetched as needed through the use of
`go run`.

This allows usage in containers / build-environments without prior
setup.

### Add Makefile targets for Grafana Cloud workflow with Grizzly

Add tool dependency on `github.com/google/go-jsonnet/cmd/jsonnet` and
build dashboards in Makefile (pattern rule for `%.jsonnet` to `%.yaml`)
and `gc-resources` target.

Add tool dependency on `github.com/grafana/grizzly/cmd/grr` and make
targets `gc-diff`, `gc-apply` and `gc-preview` for workflows with
Grafana Cloud.

### Convert Grafana Analytics dashboard for use with Grizzly

Add dependency on `github.com/grafana/jsonnet-libs` and use it to
automatically convert the "Grafana Analytics" dashboard into a
Kubernetes-style resource for use with Grizzly. This allows it to be
used with make `gc-*` targets.

Extend `stdlib.jsonnet` helper with a `toResource()` method to allow
converting Grafonnet dashboards easily.

### Checklist

- [ ] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Comment by mig4** [comment]
## TODO

- [ ] extend to other Grafana Cloud _official_ dashboards (currently only works on _Grafana Analytics_ dashboard)
- [ ] allow specifying a single dashboard to diff/apply/preview
- [ ] replace scripts and fix CI

**Comment by mig4** [comment]
Couple of things still to do :arrow_up: but I wanted to get feedback on if you see any big issues with this approach or just see any other improvements that need to be made before this can land.

**Comment by JosephSalisbury** [comment]
I think I might need to see a demo of this at some point :D

**Comment by QuentinBisson** [comment]
You missed it :D It was awesome :)

**Review by TheoBrigitte — COMMENTED** [review]
I like this and saw it working live <3

Just one thing, could we add all the new command under `make help` somehow? I find this pretty handy. Current `make help`:
```
$ make help

Usage:
  make <target>

General
  help                  Display this help.
  clean                 Clean (delete) all outputs
  vendor                Fetch Jsonnet dependencies
  gc-resources          Grafana Cloud resources

App
  lint-chart            Runs ct against the default chart.
```

**Comment by mig4** [comment]
> Just one thing, could we add all the new command under `make help` somehow? I find this pretty handy. Current `make help`:

Oh yes, I forgot to update that. Done now:

``` sh
❯ make help

Usage:
  make <target>

General
  help                  Display this help.
  clean                 Clean (delete) all outputs
  vendor                Fetch Jsonnet dependencies
  gc-resources          generate Grafana Cloud resource (dashboards, folders) YAML files
  gc-diff               show a diff between locally generated resources and Grafana Cloud
  gc-apply              apply (upload) resources generated by gc-resources to Grafana Cloud
  gc-preview            preview locally modified dashboards on Grafana Cloud

App
  lint-chart            Runs ct against the default chart.
```

**Comment by mig4** [comment]
> I think I might need to see a demo of this at some point :D

I can do another demo just for you :wink:

**Comment by snizhana-dynnyk** [comment]
Closing due to the lack of bandwidth.

**Pull request closed without merging**
