### PR TITLE
Added cache panel and allocatable thresholds to k8s-resources-node dashboard

### PR DESCRIPTION
**Pull request by weseven**
This PR

- adds a cache graph to the memory usage panels
- adds allocatable thresholds to CPU and Memory usage graphs 

Towards https://github.com/giantswarm/giantswarm/issues/29818

image

### Checklist

- [x] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Comment by QuentinBisson** [comment]
@weseven have you checked that the newer mixins might fix it?

**Comment by QuentinBisson** [comment]
So i'm fine with your change but could you open a pr on thé upstream mixin to also add it there ? Because this might bé Lost when WE finally start managing mixins properly

**Comment by weseven** [comment]
Opened https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/895 to add the `max allocatable` threshold and https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/896 to add the "Cache usage" panel to the upstream mixin repo.

**Comment by weseven** [comment]
Can this be approved/merged in the meantime? Unfortunately the upstream mixin repo doesn't seem very active :(

**Review by QuentinBisson — APPROVED** [review]
Of course, sorry about the delay. I thought I approved

**Pull request merged**
