### PR TITLE
Add mimir write mixin dashboard 

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
Towards https://github.com/giantswarm/roadmap/issues/3162

This PR adds the mimir mixin dashboards. Maybe they're all not needed, let's discuss about that

### Checklist

- [x] Update changelog in CHANGELOG.md in an end-user friendly language.

### CODE REVIEW

**Comment by QuantumEnigmaa** [comment]
I'm currently doing it :)

**Comment by hervenicol** [comment]
It would be nice to add a document explaining where these dashboards come from, and what you had to do to fix them.
Like here: https://github.com/giantswarm/dashboards/tree/master/loki

**Comment by QuantumEnigmaa** [comment]
Some graph display interesting data but most of them will need to be adapted to our setup : 
image
image

**Comment by QuentinBisson** [comment]
Would you think it makes sense that we add them one by one ? Because we probably don't need them all, yet and also because fixing and screenshottig will bé easier

**Comment by QuantumEnigmaa** [comment]
This is what the dashboard looks like currently (at least the most interesting parts) : 
image

image

On the second screenshot, one can have an overview of the regular cycles where the ingester uploads its data to the object storage.

**Comment by QuentinBisson** [comment]
This is nice :)

Maybe we could reduce the interval between compactions :D

**Comment by QuentinBisson** [comment]
Do you want to add the others in this PR ? If not,can you list hte dashboards we want to add in the parent issue?

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuantumEnigmaa** [comment]
> Maybe we could reduce the interval between compactions :D

Yeah, but this is outside of the scope for this issue x)
But I agreee that if possible, it could be nice to reduce it to save on resources !

> Do you want to add the others in this PR ? If not,can you list hte dashboards we want to add in the parent issue?

I will create other PRs for the other dashboards and I'll write those ones in the issue :)

**Comment by QuantumEnigmaa** [comment]
Sorry, late change in plans : I'm also adding the `writes-resources` dashboard in this PR as it's write related :bow:

**Comment by QuantumEnigmaa** [comment]
Apart from the disk storage graphs (which I'm currently working on), we have nice data : 
image

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuantumEnigmaa** [comment]
Woops my bad sorry

**Pull request merged**
